config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :visitors
  devise_for :place_owners
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  #get "details/details" => "details#details"
  resources :places, only: [:show, :new, :create, :destroy] do
    get 'my_places', on: :collection
    resources :place_reservations, only: %i[create show new index] do
      post 'accept', on: :member
    end
  end
#  resources :place_reservations, only: %i[show]
  resources :place_types, only: [:show, :new, :create]
  resources :place_regions, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :place_type
  belongs_to :place_region
  belongs_to :place_owner
  has_many :place_reservation, dependent: :destroy

  validates :title, :description, :rooms, :bathrooms, :rent, presence: true
end

app/models/place_owner.rb
class PlaceOwner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :place
end

app/models/place_region.rb
class PlaceRegion < ApplicationRecord
  has_many :place
  validates :name, presence: {message: 'região não pode ficar em branco'}
  validates :name, uniqueness: {message: 'região já existente'}
end

app/models/place_reservation.rb
class PlaceReservation < ApplicationRecord
  belongs_to :place
  belongs_to :visitor

  validate :end_date_greater_than_start_date, :start_date_in_the_past #funcionando no teste mas não no server

  enum status: {pending: 0, accepted: 1, rejected: 2}




  private

  def end_date_greater_than_start_date
    if start_date >= end_date then
      errors.add(:end_date, 'deve ser maior que a data de início')
    end
  end

  def start_date_in_the_past
    if start_date < Date.today then
      errors.add(:start_date, 'deve ser maior que a data atual')
    end
  end
end

app/models/place_type.rb
class PlaceType < ApplicationRecord
  has_many :place 
  validates :name, presence: {message: 'tipo não pode ficar em branco'}
  validates :name, uniqueness: {message: 'tipo já existente'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :place_reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @places = Place.all()
    @place_type = PlaceType.all()
    @place_region = PlaceRegion.all()
  end
end

app/controllers/place_regions_controller.rb
class PlaceRegionsController < ApplicationController
  def show
    id = params[:id]
    @place_region = PlaceRegion.find(id)
  end

  def new
    @place_region = PlaceRegion.new
  end

  def create
    @place_region = PlaceRegion.create(params.require(:place_region).permit(:name))
    if @place_region.persisted? then
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/place_reservations_controller.rb
class PlaceReservationsController < ApplicationController
  def new
    @place_reservation = PlaceReservation.new
  end

  def show
    @place_reservation = PlaceReservation.find(params[:id])
  end

  def accept
    @place_reservation = PlaceReservation.find(params[:id])
    @place_reservation.accepted!
    redirect_to @place_reservation.place
  end

  def create
    @place_reservation = PlaceReservation.new(place_reservation_params)
    @place_reservation.visitor = current_visitor
    @place_reservation.place = Place.find(params[:place_id])
    @place_reservation.save

    redirect_to root_path, notice: 'Pedido de reserva enviado' #deveria redirectar to place_reservations/show mas não funciona por algum motivo
  end

  private

  def place_reservation_params
    params.require(:place_reservation).permit(:start_date, :end_date, :guests, :place_id)
  end
end

app/controllers/place_types_controller.rb
class PlaceTypesController < ApplicationController
  def show
    id = params[:id]
    @place_type = PlaceType.find(id)
  end

  def new
    @place_type = PlaceType.new
  end

  def create
    @place_type = PlaceType.create(params.require(:place_type).permit(:name))
    if @place_type.persisted? then
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_place_owner!, only: [:new, :create]

  def show
    id = params[:id]
    @places = Place.find(id)
    @place_reservations = @places.place_reservation.new
  end

  def new
    @places = Place.new
  end

  def create
    @places = Place.new(params.require(:place).permit(:title, :description, :rooms, :bathrooms, :rent, :pets, :parking_slot, :place_type_id, :place_region_id))
    @places.place_owner = current_place_owner
    if @places.save then
      redirect_to place_path(@places.id)
    else
      render :new
    end
  end

  def destroy
    id = params[:id]
    @places = Place.destroy(id)
    redirect_to root_path
  end

  def my_places
    @places = current_place_owner.place
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/details.html.erb
<% @places.each do |p| %>
  <%=p.title%>
  <%=p.description%>
  Quartos: <%=p.rooms%>
  Banheiros: <%=p.bathrooms%>
  Aceita pets: <%= if p.pets == true then "Sim" else "Não" end %>
  Estacionamento: <%= if p.parking_slot == true then "Sim" else "Não" end%>
  Diária: R$<%=p.rent%>
<% end %>

app/views/home/index.html.erb
<header>
  <h1>Flats</h1>
  <h3>Boas vindas ao sistema de locação de apartamentos</h3>
</header>

<aside>
  <h4>Filtrar por tipo:</h4>
  <nav>
    <% @place_type.each do |pt| %>
      <%= link_to pt.name, place_type_path(pt.id) %> <br>
    <%end%>
    <%= link_to '> Criar novo tipo', new_place_type_path %>
  </nav>
</aside>

<aside>
  <h4>Filtrar por região:</h4>
  <nav>
    <% @place_region.each do |pr| %>
      <%= link_to pr.name, place_region_path(pr.id) %> <br>
    <%end%>
    <%= link_to '> Criar nova região', new_place_region_path %>
  </nav>
</aside>

<section>
  <h4> Imóveis disponíveis: </h4>
  <% if @places.empty? then %>
    Nenhum imóvel disponível
  <% end %>
  <nav>
    <% @places.each do |p| %>
      <%=link_to(p.title, place_path(p.id)) %>
      <%=p.description%>
      Quartos: <%=p.rooms%>
      <br>
    <%end%>
  </nav>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if place_owner_signed_in? %>
        <p><%= link_to 'Meus imóveis', my_places_places_path %></p>
        <p><%= link_to 'Cadastrar imóvel', new_place_path %></p>
        <p><%= current_place_owner.email %></p>
        <p><%= link_to 'Logout', destroy_place_owner_session_path, method: :delete %></p>
      <% else %>
        <p><%= link_to 'Entrar', new_place_owner_session_path %></p>
      <% end %>
    </nav>
    <p><%= flash[:notice] %></p>
    <p><%= flash[:alert] %></p>
    <%= yield %>
  </body>
</html>

app/views/place_regions/new.html.erb
<% if @place_region.errors.any? then %>
  <% @place_region.errors.full_messages.each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<%= form_with(model: PlaceRegion.new) do |pr| %>
    <%= pr.label :name, 'Nova região: ' %>
    <%= pr.text_field :name %>
    <%= pr.submit 'Enviar' %>
<%end%>

app/views/place_regions/show.html.erb
<h1>Imóveis na região: <%=@place_region.name%></h1>
</br>

<%@place_region.place.each do |pr| %>
<%=link_to(pr.title, place_path(pr.id)) %>
<%end%>

app/views/place_reservations/show.html.erb
<h3>Reserva de imóvel <%= @place_reservation.place.title%> </h3>
Data de início: <%= @place_reservation.start_date %>
Data de término: <%= @place_reservation.end_date %>

app/views/place_type/new.html.erb
<%= form_with(model: PlaceType.new) do |pt| %>
    <%= pt.label :name, 'Nome do tipo: ' %>
    <%= pt.text_field :name %>
    <%= pt.submit 'Enviar' %>
<%end%>

app/views/place_types/new.html.erb
<% if @place_type.errors.any? then %>
  <% @place_type.errors.full_messages.each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<%= form_with(model: PlaceType.new) do |pt| %>
    <%= pt.label :name, 'Novo tipo: ' %>
    <%= pt.text_field :name %>
    <%= pt.submit 'Enviar' %>
<%end%>

app/views/place_types/show.html.erb
<h1>Imóveis do tipo: <%=@place_type.name%></h1>
</br>

<%@place_type.place.each do |pt| %>
<%=link_to(pt.title, place_path(pt.id)) %>
<%end %>

app/views/places/my_places.html.erb
<h1>Meus imóveis</h1>
<% if @places.empty? then %>
  Você ainda não cadastrou nenhum imóvel
  <%= link_to 'Cadastrar seu primeiro imóvel', new_place_path %>
<% end %>
<% @places.each do |p| %>
  <%= link_to(p.title, place_path(p.id)) %>
<%end%>

app/views/places/new.html.erb
<h1>Cadastro de Imóvel</h1>

<% if @places.errors.any? then %>
  <% @places.errors.full_messages.each do |error| %>
    <%= error %>
  <% end %>
<% end %>


<%= form_with(model: Place.new) do |f| %>
  <div>
    <%= f.label :place_type_id, "Tipo" %>
    <%= f.collection_select :place_type_id, PlaceType.all, :id, :name %>
  </div>
  <div>
    <%= f.label :place_region_id, "Região" %>
    <%= f.collection_select :place_region_id, PlaceRegion.all, :id, :name %>
  </div>
  <div>
    <%= f.label :title%>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.label :rooms %>
    <%= f.number_field :rooms %>
  </div>
  <div>
    <%= f.label :bathrooms %>
    <%= f.number_field :bathrooms %>
  </div>
  <div>
    <%= f.label :rent, 'Diária' %>
    <%= f.number_field :rent %>
  </div>
  <div>
    <%= f.label :pets %>
    <%= f.check_box :pets %>
  </div>
  <div>
    <%= f.label :parking_slot, 'Tem garagem' %>
    <%= f.check_box :parking_slot %>
  </div>
  <%= f.submit 'Enviar' %>
<%end%>

app/views/places/show.html.erb
<% p = @places %>
  <%=p.title%>
  <%=p.description%>
  Quartos: <%=p.rooms%>
  Banheiros: <%=p.bathrooms%>
  Aceita pets: <%= if p.pets == true then "Sim" else "Não" end %>
  Estacionamento: <%= if p.parking_slot == true then "Sim" else "Não" end%>
  Diária: <%=number_to_currency(p.rent)%>
  Tipo: <%=p.place_type.name%>
  Região: <%=p.place_region.name%>
  Proprietário: <%= p.place_owner.email %>


<% if place_owner_signed_in? && @places.place_owner == current_place_owner then %>
<%= link_to 'Apagar', place_path(@places), method: :delete%>
  <h3>Reservas</h3>
  <% @places.place_reservation.each do |pr| %>
    <h4>Reserva de <%= pr.visitor  %></h4> <!--.email should work, for some reason doesn't -->
    Data de início: <%= pr.start_date %>
    Data de final: <%= pr.end_date %>
    Status: <%= pr.status %>
    <% if pr.pending? then %>
      <%= link_to "Aceitar reserva", accept_place_place_reservation_path(pr.place_id), method: :post %>
    <%end%>
  <%end%>
<%elsif visitor_signed_in? %>
  <h3>Reserve agora:</h3>
  <%= form_with model: [@places, @place_reservations] do |f| %>
    <%= f.label :start_date, 'Data inicial' %>
    <%= f.date_field :start_date %>
    <%= f.label :end_date, 'Data final' %>
    <%= f.date_field :end_date %>
    <%= f.label :guests, 'Quantidade de pessoas' %>
    <%= f.number_field :guests, step: 1, min: 1 %>
    <%= f.submit 'Requisitar reserva' %>
  <% end %>
<%end%>

<br><%= link_to "Voltar", root_path %>